version: "3.7"

services: 
  frontend:
    container_name: frontend
    build: 
      context : ./frontend
    command: yarn start
    stdin_open: true
    tty: true
    volumes: 
      - ./frontend/src:/usr/app/src
    ports:
      - "3000:3000"

  api:
    container_name: api
    build: 
      context: ./api
    environment: 
      - PORT=3001
      - URL="http://localhost"
      - DB_NAME=deno-todo
      - MONGO_URL=mongodb://api_mongo:27017
    volumes: 
      - ./api/src:/usr/app/src
    ports:
      - "3001:3001"

  api_mongo:
    image: mongo:latest
    container_name: api_mongo
    volumes: 
      - mongodb_api_volume:/data/db
    ports: 
      - "27017:27017"


volumes: 
  mongodb_api_volume:
    name: mongodb_api_volume
